### ISSUE TITLE
Create functionality to delete account with all of it's dependencies.

### ISSUE THREAD

**Issue by deviserops** [deviserops/dj-all-auth#1]
When user try to delete his account: 

1.  First
-> Show popup and ask if he really want to delete his account 
-> Show a small description that all of it's dependencies will be deleted with it.
-> Like deleting all related model data with user model data (Mean his own account)

2. Second
-> Add option in settings for user delete option for soft delete or hard delete (Must be boolean)
-> Default it will be soft delte mean user will be only `is_active=False`

Note: Please read `CONTRIBUTING.md` first.

**Comment by Alexandros76** [comment]
delete the account as this refers to companies and I don't not have a company. I open the account by mistake
